Better build process

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,21 +1,5 @@
 #!/bin/sh
 
-findlib() {
-	lib=$1
-	arg=$2
-	for p in / /usr /usr/local /opt/local $arg
-	do
-		if test -d $p &&
-		   find $p/lib/x86_64-linux-gnu -maxdepth 1 -name lib$lib\* |
-		     grep '$' > /dev/null
-		then
-			echo $p
-			return
-		fi
-	done
-	echo "✗ could not find library $lib" 1>&2
-}
-
 if test -f config.mk
 then
 	# Reload last configuration
@@ -29,11 +13,9 @@ usage: ./configure [options]
 Options:
 	-prefix PATH      The installation prefix path
 	-prefix=PATH
-	-gmp PATH         The directory containing the GMP library
-	-mpfr PATH        The directory containing the MPFR library
-	-gsl PATH 		  The path containing the GSL library
+	-clp PATH         The directory containing the CLP library
+	-coin-utils PATH  The directory containing the Coin-Or utilities
 
-	-llvm-config CMD  The name used to invoke llvm-config
 	-cxx CMD          The C++ compiler to use (must support C++11)
 	-cc CMD           The C compiler to use (must support C99)
 
@@ -44,9 +26,10 @@ EOM
 
 TOOL_NAME=absynth-cuda
 OUR_PREFIX=/usr
-LLC=llvm-config
 CXX=c++
 CC=cc
+CLP_PREFIX=/usr/local
+CUTILS_PREFIX=/usr/local/include/coin-or
 
 while test $# -gt 0
 do
@@ -61,24 +44,14 @@ do
 		OUR_PREFIX=$1
 		shift
 		;;
-	--gmp|-gmp)
+	--clp|-clp)
 		test $# -gt 0 || usage
-		GMP_PREFIX=$(dirname $1)
+		CLP_PREFIX=$1
 		shift
 		;;
-	--mpfr|-mpfr)
+	--coin-utils|-coin-utils)
 		test $# -gt 0 || usage
-		MPFR_PREFIX=$(dirname $1)
-		shift
-		;;
-	--gsl|-gsl)
-		test $# -gt 0 || usage
-		GSL_PREFIX=$(dirname $1)
-		shift
-		;;
-	--llvm-config|-llvm-config)
-		test $# -gt 0 || usage
-		LLC=$1
+		CUTILS_PREFIX=$1
 		shift
 		;;
 	--cc|-cc)
@@ -129,53 +102,32 @@ then
 	exit 1
 fi
 
-# if false; then
-if ! ( $LLC --version; ) > /dev/null 2>&1
+if !( test -f "$CLP_PREFIX/lib/libClp.a"; )
 then
-	LLC=
-	echo "✗ warning: llvm-config not found, llvm-reader will not be built"
+	echo "✗ libClp not found" 1>&2
+	exit 1
 fi
-#fi
-#LLC=
-
-GMP_PREFIX=$(findlib gmp $GMP_PREFIX)
-#test -n "$GMP_PREFIX" || exit 1
-
-MPFR_PREFIX=$(findlib mpfr $MPFR_PREFIX)
-#test -n "$MPFR_PREFIX" || exit 1
-
-GSL_PREFIX=$(findlib gsl $GSL_PREFIX)
-#test -n "$GSL_PREFIX" || exit 1
 
 cat > config.mk << EOF
 # Automatically generated by the configure script.
 
 TOOL_NAME=$TOOL_NAME
 OUR_PREFIX=$OUR_PREFIX
-GMP_PREFIX=$GMP_PREFIX
-MPFR_PREFIX=$MPFR_PREFIX
-GSL_PREFIX=$GSL_PREFIX
+CLP_PREFIX=$CLP_PREFIX
+CUTILS_PREFIX=$CUTILS_PREFIX
 CXX=$CXX
 CC=$CC
-LLC=$LLC
 EOF
 
-if test -z $LLC
-then
-	buildllvm=no
-else
-	buildllvm=yes
-fi
 
 cat << EOM
 Configuration:
 
    Installation prefix: $OUR_PREFIX
-   MPFR library in:     $MPFR_PREFIX
-   GMP library in:      $GMP_PREFIX
-   GSL library in:      $GSL_PREFIX
+   CLP library in:      $CLP_PREFIX
+   CoinUtils in:        $CUTILS_PREFIX
    C++ compiler:        $CXX
    C compiler:          $CC
-   Build llvm-reader:   $buildllvm
 
 EOM
+
